### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by dgcasey0325** [jaspax/machete#1]
It appears the Bid Optimization is missing on the Keyword screen. any chance this will get fixed?

**Comment by jaspax** [comment]
Thanks for bringing this to my attention. Can you give me the URL of the
page that this is on? I suspect that Amazon has changed something which is
preventing the tab grin showing up, since we haven't made any recent
changes to Machete.

**Comment by jaspax** [comment]
We pushed an update out this morning that should resolve the issue. Let us know if you have any other problems.
