### ISSUE TITLE
Machete goes grey

### ISSUE THREAD

**Issue by sigetty** [jaspax/machete#2]
Hello
The last couple of days the Machete logo in the browser is grey, and the campaign management page for the ad is without fx optimizing. It looks like this. (I have restarted the computer and browser) 
<img width="807" alt="screen shot 2018-04-13 at 1 37 36 pm" src="https://user-images.githubusercontent.com/5984714/38749573-0d6996e0-3f20-11e8-8e27-d4ee4445262a.png">

**Comment by jaspax** [comment]
We pushed an update out this morning that resolves the issue. Let us know if you have any extra problems.
