### ISSUE TITLE
Advertising data not showing past 9/2/2018

### ISSUE THREAD

**Issue by osheab87** [jaspax/machete#4]
I am unable to see any data collected after 9/2/2018 in all views.

Here is an example from Advertising campaigns » Campaign Management >> Campaign History tab. When I try to click on a date past 9/2/2018, it defaults back to 9/2/2018.
![2018-09-10_19-29-55](https://user-images.githubusercontent.com/43008110/45334588-41b15b00-b530-11e8-8a52-ce0608dcd315.gif)

Here is an screenshot form the Advertising Campaigns home screen plots for an activley running campaign. 
![image](https://user-images.githubusercontent.com/43008110/45334306-08c4b680-b52f-11e8-8bde-987a47eab617.png)

Let me know if there is any other useful information I can provide to help you debug.

**Comment by jaspax** [comment]
Should be fixed by the checkins leading up to https://github.com/jaspax/machete/commit/61a204131c95365dffe6b0c605a15775fbd40f6f
